# Generated by Django 5.1.3 on 2025-01-13 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nCUSCODE', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nCTId', models.IntegerField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=False)),
                ('nComName', models.CharField(blank=True, max_length=255, null=True)),
                ('nSurName', models.CharField(blank=True, max_length=255, null=True)),
                ('nFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress1', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress2', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress3', models.CharField(blank=True, max_length=255, null=True)),
                ('nCity', models.CharField(blank=True, max_length=100, null=True)),
                ('nState', models.CharField(blank=True, max_length=100, null=True)),
                ('nPostCode', models.CharField(blank=True, max_length=20, null=True)),
                ('nPhone1', models.CharField(blank=True, max_length=20, null=True)),
                ('nPhone2', models.CharField(blank=True, max_length=20, null=True)),
                ('nMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('nFax', models.CharField(blank=True, max_length=20, null=True)),
                ('nEmail', models.EmailField(blank=True, max_length=255, null=True)),
                ('nWebsite', models.URLField(blank=True, max_length=255, null=True)),
                ('nCreditLimit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nVAT', models.BooleanField(default=False)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('nSMS', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bibs_customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nEMPCODE', models.CharField(max_length=50, unique=True)),
                ('nUserRole', models.IntegerField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=False)),
                ('nFirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('nSurName', models.CharField(blank=True, max_length=100, null=True)),
                ('nAddress1', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress2', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress3', models.CharField(blank=True, max_length=255, null=True)),
                ('nTown', models.CharField(blank=True, max_length=100, null=True)),
                ('nPostCode', models.CharField(blank=True, max_length=20, null=True)),
                ('nPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('nMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('nEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('nBasicSal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nOverTime', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nNoOfAppLeave', models.IntegerField(default=0)),
                ('nLeaveTaken', models.IntegerField(default=0)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('nFSID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nImage', models.TextField(blank=True, null=True)),
                ('nPwdHash', models.CharField(blank=True, max_length=256, null=True)),
                ('nPwdSalt', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nJOBCODE', models.CharField(max_length=50, unique=True)),
                ('nJStatID', models.IntegerField()),
                ('nIQty', models.IntegerField(default=1)),
                ('nPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nFSID', models.UUIDField(blank=True, default=None, null=True)),
                ('nImage', models.TextField(blank=True, null=True)),
                ('nItem', models.CharField(blank=True, max_length=255, null=True)),
                ('nMetal', models.CharField(blank=True, max_length=255, null=True)),
                ('nJobDesc', models.TextField(blank=True, null=True)),
                ('nJobDescHTML', models.TextField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_jobs',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MItem',
            fields=[
                ('it_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('seq_no', models.CharField(max_length=10)),
                ('nActive', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nitems',
            },
        ),
        migrations.CreateModel(
            name='MMetal',
            fields=[
                ('met_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('nActive', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nmetals',
            },
        ),
        migrations.CreateModel(
            name='MMetalProcess',
            fields=[
                ('mepr_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('nActive', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nmetalprocess',
            },
        ),
        migrations.CreateModel(
            name='MProcess',
            fields=[
                ('pr_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('pipe', models.CharField(max_length=50)),
                ('nActive', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nprocess',
            },
        ),
        migrations.CreateModel(
            name='NAccountSummary',
            fields=[
                ('nID', models.BigAutoField(primary_key=True, serialize=False)),
                ('nACUSID', models.CharField(max_length=50)),
                ('nTickets', models.DecimalField(decimal_places=10, max_digits=20)),
                ('nPayment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nTotOutStand', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nAccountSummary',
            },
        ),
        migrations.CreateModel(
            name='NItemResizeType',
            fields=[
                ('itmrz_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nType', models.CharField(max_length=50)),
                ('nSeqNo', models.IntegerField()),
                ('nActive', models.BooleanField(default=False)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nitemresizetype',
            },
        ),
        migrations.CreateModel(
            name='NProcessPipeType',
            fields=[
                ('nPTId', models.AutoField(primary_key=True, serialize=False)),
                ('nProType', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NProcessType',
            fields=[
                ('pt_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('processName', models.CharField(max_length=50)),
                ('processPipe', models.CharField(max_length=50)),
                ('nActive', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nprocesstype',
            },
        ),
        migrations.CreateModel(
            name='SerialTable',
            fields=[
                ('sr_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'serial_table',
            },
        ),
        migrations.CreateModel(
            name='SetupCompany',
            fields=[
                ('company_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('vat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'setup_company',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user_groups',
            },
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nTKTCODE', models.CharField(max_length=50)),
                ('nJOBCODE', models.CharField(max_length=50)),
                ('img_id', models.CharField(max_length=100, unique=True)),
                ('img_location', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bibs.job')),
            ],
            options={
                'db_table': 'tb_jobs_images',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('nTKTCODE', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nStatID', models.IntegerField()),
                ('nDocNo', models.CharField(blank=True, max_length=50, null=True)),
                ('nDueDate', models.DateField()),
                ('nDueTime', models.TimeField()),
                ('nTItems', models.IntegerField(default=0)),
                ('nCalVat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nCostNoVAT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nTCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nTPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nTDue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multipleImages', models.BooleanField(default=False)),
                ('isCashCustomer', models.BooleanField(default=False)),
                ('isCusNotSigned', models.BooleanField(default=False)),
                ('nFSID', models.UUIDField(blank=True, default=None, null=True)),
                ('nCusSignImage', models.TextField(blank=True, null=True)),
                ('nComments', models.TextField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=True)),
                ('nInvoice', models.BooleanField(default=False)),
                ('nAcceptedDate', models.DateTimeField(auto_now_add=True)),
                ('nReadyDate', models.DateTimeField(blank=True, null=True)),
                ('nReleasedDate', models.DateTimeField(blank=True, null=True)),
                ('nAcceptedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nReadyBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nReleasedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='nCUSCODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bibs.customer')),
            ],
            options={
                'db_table': 'tb_tickets',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='ticket',
            field=models.ForeignKey(db_column='nTKTCODE', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='bibs.ticket'),
        ),
        migrations.CreateModel(
            name='MenuAccessVisibility',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
                ('visible_no', models.CharField(blank=True, max_length=10, null=True)),
                ('user_group', models.ForeignKey(db_column='user_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_access', to='bibs.usergroup')),
            ],
            options={
                'db_table': 'menu_access_visibility',
            },
        ),
        migrations.CreateModel(
            name='MTrsItemsMetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField(default=0)),
                ('item', models.ForeignKey(db_column='it_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.mitem')),
                ('metal', models.ForeignKey(db_column='met_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.mmetal')),
            ],
            options={
                'db_table': 'M_trs_items_metals',
                'unique_together': {('item', 'metal')},
            },
        ),
        migrations.CreateModel(
            name='MTrsMetalMetalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField(default=0)),
                ('metal', models.ForeignKey(db_column='met_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.mmetal')),
                ('metal_process', models.ForeignKey(db_column='mepr_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.mmetalprocess')),
            ],
            options={
                'db_table': 'M_trs_metals_metalprocess',
                'unique_together': {('metal_process', 'metal')},
            },
        ),
        migrations.CreateModel(
            name='MTrsProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField(default=0)),
                ('metal_process', models.ForeignKey(db_column='mepr_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.mmetalprocess')),
                ('process', models.ForeignKey(db_column='pr_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.mprocess')),
            ],
            options={
                'db_table': 'M_trs_process',
                'unique_together': {('metal_process', 'process')},
            },
        ),
        migrations.CreateModel(
            name='MTrsProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField(default=0)),
                ('process', models.ForeignKey(db_column='pr_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.mprocess')),
                ('process_type', models.ForeignKey(db_column='pt_id', on_delete=django.db.models.deletion.CASCADE, to='bibs.nprocesstype')),
            ],
            options={
                'db_table': 'M_trs_process_type',
                'unique_together': {('process_type', 'process')},
            },
        ),
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('access_right_id', models.AutoField(primary_key=True, serialize=False)),
                ('add', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='bibs.menu')),
                ('user_group', models.ForeignKey(db_column='user_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='bibs.usergroup')),
            ],
            options={
                'db_table': 'access_rights',
                'unique_together': {('user_group', 'menu')},
            },
        ),
    ]
