# Generated by Django 5.1.3 on 2024-12-01 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nEMPCODE', models.CharField(max_length=50, unique=True)),
                ('nUserRole', models.IntegerField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=False)),
                ('nFirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('nSurName', models.CharField(blank=True, max_length=100, null=True)),
                ('nAddress1', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress2', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress3', models.CharField(blank=True, max_length=255, null=True)),
                ('nTown', models.CharField(blank=True, max_length=100, null=True)),
                ('nPostCode', models.CharField(blank=True, max_length=20, null=True)),
                ('nPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('nMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('nEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('nBasicSal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nOverTime', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nNoOfAppLeave', models.IntegerField(default=0)),
                ('nLeaveTaken', models.IntegerField(default=0)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
                ('nCreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nUpdatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nFSID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nImage', models.TextField(blank=True, null=True)),
                ('nPwdHash', models.CharField(blank=True, max_length=256, null=True)),
                ('nPwdSalt', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
