# Generated by Django 5.1.3 on 2024-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitem',
            old_name='date_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='mmetal',
            old_name='date_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='mmetalprocess',
            old_name='date_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='setupcompany',
            old_name='date_time',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='mitem',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='mmetal',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='mmetalprocess',
            name='userid',
        ),
        migrations.AddField(
            model_name='mitem',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mitem',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mitem',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mmetal',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mmetal',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mmetal',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mmetalprocess',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mmetalprocess',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mmetalprocess',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='setupcompany',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setupcompany',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setupcompany',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
