# Generated by Django 5.1.3 on 2025-01-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupcompany',
            name='vat_no',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
