# Generated by Django 5.1.3 on 2024-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nCUSCODE', models.CharField(max_length=50, unique=True)),
                ('nCTId', models.IntegerField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=False)),
                ('nComName', models.CharField(blank=True, max_length=255, null=True)),
                ('nSurName', models.CharField(blank=True, max_length=255, null=True)),
                ('nFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress1', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress2', models.CharField(blank=True, max_length=255, null=True)),
                ('nAddress3', models.CharField(blank=True, max_length=255, null=True)),
                ('nCity', models.CharField(blank=True, max_length=100, null=True)),
                ('nState', models.CharField(blank=True, max_length=100, null=True)),
                ('nPostCode', models.CharField(blank=True, max_length=20, null=True)),
                ('nPhone1', models.CharField(blank=True, max_length=20, null=True)),
                ('nPhone2', models.CharField(blank=True, max_length=20, null=True)),
                ('nMobile', models.CharField(blank=True, max_length=20, null=True)),
                ('nFax', models.CharField(blank=True, max_length=20, null=True)),
                ('nEmail', models.EmailField(blank=True, max_length=255, null=True)),
                ('nWebsite', models.URLField(blank=True, max_length=255, null=True)),
                ('nCreditLimit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nVAT', models.BooleanField(default=False)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
                ('nCreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nUpdatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nSMS', models.BooleanField(default=False)),
            ],
        ),
    ]
