# Generated by Django 5.1.3 on 2024-11-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0002_mitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMetal',
            fields=[
                ('met_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MMetalProcess',
            fields=[
                ('mepr_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
