# Generated by Django 5.1.3 on 2024-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0003_mmetal_mmetalprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialTable',
            fields=[
                ('sr_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
