# Generated by Django 5.1.3 on 2025-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0003_alter_setupcompany_vat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='isCusNotSigned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nStatID',
            field=models.IntegerField(default=1),
        ),
    ]
