# Generated by Django 5.1.3 on 2024-12-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nActive',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nAddress1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nAddress2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nAddress3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nCTId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nCity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nComName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nCreatedBy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nCreditLimit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nEmail',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nFax',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nFirstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nMobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nPhone1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nPhone2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nPostCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nSMS',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nState',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nSurName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nUpdatedBy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nVAT',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nWebsite',
            field=models.URLField(max_length=255),
        ),
    ]
