# Generated by Django 5.1.3 on 2025-01-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0004_alter_ticket_iscusnotsigned_alter_ticket_nstatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nFSID',
            field=models.IntegerField(default=1),
        ),
    ]
