# Generated by Django 5.1.3 on 2025-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0005_alter_ticket_nfsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='isCashCustomer',
            field=models.IntegerField(default=0),
        ),
    ]
