# Generated by Django 5.1.3 on 2024-12-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0005_alter_customer_nactive_alter_customer_naddress1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nTKTCODE', models.CharField(max_length=20, unique=True)),
                ('nStatID', models.IntegerField()),
                ('nDocNo', models.CharField(blank=True, max_length=50, null=True)),
                ('nDueDate', models.DateField()),
                ('nDueTime', models.TimeField()),
                ('nTItems', models.IntegerField(default=0)),
                ('nCalVat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nCostNoVAT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nTCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nTPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nTDue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multipleImages', models.BooleanField(default=False)),
                ('isCashCustomer', models.BooleanField(default=False)),
                ('isCusNotSigned', models.BooleanField(default=False)),
                ('nFSID', models.UUIDField(blank=True, default=None, null=True)),
                ('nCusSignImage', models.TextField(blank=True, null=True)),
                ('nComments', models.TextField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=True)),
                ('nInvoice', models.BooleanField(default=False)),
                ('nAcceptedDate', models.DateTimeField(blank=True, null=True)),
                ('nReadyDate', models.DateTimeField(blank=True, null=True)),
                ('nReleasedDate', models.DateTimeField(blank=True, null=True)),
                ('nAcceptedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nReadyBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nReleasedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bibs.customer')),
            ],
            options={
                'db_table': 'tb_tickets',
            },
        ),
    ]
