# Generated by Django 5.1.3 on 2024-12-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0006_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nJOBCODE', models.CharField(max_length=50, unique=True)),
                ('nJStatID', models.IntegerField()),
                ('nIQty', models.IntegerField(default=1)),
                ('nPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nFSID', models.UUIDField(blank=True, default=None, null=True)),
                ('nImage', models.TextField(blank=True, null=True)),
                ('nItem', models.CharField(blank=True, max_length=255, null=True)),
                ('nMetal', models.CharField(blank=True, max_length=255, null=True)),
                ('nJobDesc', models.TextField(blank=True, null=True)),
                ('nJobDescHTML', models.TextField(blank=True, null=True)),
                ('nActive', models.BooleanField(default=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='bibs.ticket')),
            ],
            options={
                'db_table': 'tb_jobs',
            },
        ),
    ]
