# Generated by Django 5.1.3 on 2025-01-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0007_update_ntdue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPaymentType',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nType', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'NPaymentType',
            },
        ),
    ]
