# Generated by Django 5.1.3 on 2024-12-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0007_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nTKTCODE', models.CharField(max_length=50)),
                ('nJOBCODE', models.CharField(max_length=50)),
                ('img_id', models.CharField(max_length=100, unique=True)),
                ('img_location', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bibs.job')),
            ],
            options={
                'db_table': 'tb_jobs_images',
            },
        ),
    ]
