# Generated by Django 5.1.3 on 2025-01-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0008_npaymenttype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='npaymenttype',
            table='nPaymentType',
        ),
    ]
