# Generated by Django 5.1.3 on 2024-12-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0009_mmetal_seq_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmetal',
            name='seq_no',
        ),
        migrations.AddField(
            model_name='mitem',
            name='seq_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
