# Generated by Django 5.1.3 on 2025-01-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0009_alter_npaymenttype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPayment',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False)),
                ('nCusID', models.CharField(max_length=50)),
                ('nMonWeek', models.IntegerField()),
                ('nPaidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nPayType', models.IntegerField()),
                ('paymentDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('nComments', models.TextField(blank=True, null=True)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nCreatedBy', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nPayment',
            },
        ),
    ]
