# Generated by Django 5.1.3 on 2024-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0010_remove_mmetal_seq_no_mitem_seq_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtrsitemsmetals',
            name='seq_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mtrsmetalmetalprocess',
            name='seq_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mtrsprocess',
            name='seq_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nAcceptedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
