# Generated by Django 5.1.3 on 2025-02-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0010_npayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCustomer',
            fields=[
                ('cashCusID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('TicketID', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cash_customer',
            },
        ),
    ]
