# Generated by Django 5.1.3 on 2024-12-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0011_mtrsitemsmetals_seq_no_mtrsmetalmetalprocess_seq_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nId',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nId',
        ),
        migrations.AlterField(
            model_name='customer',
            name='nCUSCODE',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='ticket',
            field=models.ForeignKey(db_column='nTKTCODE', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='bibs.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(db_column='nCUSCODE', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bibs.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nTKTCODE',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='bibs_customer',
        ),
    ]
