# Generated by Django 5.1.3 on 2025-02-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0011_cashcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcustomer',
            name='vat',
            field=models.BooleanField(default=False),
        ),
    ]
