# Generated by Django 5.1.3 on 2025-02-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0012_cashcustomer_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcustomer',
            name='cashCusID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
