# Generated by Django 5.1.3 on 2024-12-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0012_remove_customer_nid_remove_ticket_nid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user_groups',
            },
        ),
    ]
