# Generated by Django 5.1.3 on 2024-12-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0013_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAccessVisibility',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
                ('visible_no', models.CharField(blank=True, max_length=10, null=True)),
                ('user_group', models.ForeignKey(db_column='user_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_access', to='bibs.usergroup')),
            ],
            options={
                'db_table': 'menu_access_visibility',
            },
        ),
    ]
