# Generated by Django 5.1.3 on 2025-02-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0013_alter_cashcustomer_cashcusid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashcustomer',
            old_name='CreatedBy',
            new_name='created_by',
        ),
    ]
