# Generated by Django 5.1.3 on 2025-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0014_rename_createdby_cashcustomer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pathimages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
