# Generated by Django 5.1.3 on 2025-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0015_remove_jobimage_img_id_remove_jobimage_ntktcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
