# Generated by Django 5.1.3 on 2024-12-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0015_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('access_right_id', models.AutoField(primary_key=True, serialize=False)),
                ('add', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='bibs.menu')),
                ('user_group', models.ForeignKey(db_column='user_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='bibs.usergroup')),
            ],
            options={
                'db_table': 'access_rights',
                'unique_together': {('user_group', 'menu')},
            },
        ),
    ]
