# Generated by Django 5.1.3 on 2025-01-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0016_accessrights'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mitem',
            table='nitems',
        ),
        migrations.AlterModelTable(
            name='mmetal',
            table='nmetals',
        ),
        migrations.AlterModelTable(
            name='mmetalprocess',
            table='nmetalprocess',
        ),
        migrations.AlterModelTable(
            name='mprocess',
            table='nprocess',
        ),
    ]
