# Generated by Django 5.2 on 2025-06-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0017_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='nPwdHash',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nPwdSalt',
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
