# Generated by Django 5.2 on 2025-06-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0018_remove_employee_npwdhash_remove_employee_npwdsalt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NProcessPipeType',
            new_name='NProcessPipeTypes',
        ),
    ]
