# Generated by Django 5.2 on 2025-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0019_rename_nprocesspipetype_nprocesspipetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.CharField(default='No description', max_length=250),
            preserve_default=False,
        ),
    ]
