# Generated by Django 5.1.3 on 2025-01-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0020_nitemresizetype_nprocesstype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nitemresizetype',
            table='nitemresizetype',
        ),
        migrations.AlterModelTable(
            name='nprocesstype',
            table='nprocesstype',
        ),
    ]
