# Generated by Django 5.2 on 2025-06-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0020_usergroup_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrights',
            old_name='edit',
            new_name='view',
        ),
    ]
