# Generated by Django 5.1.3 on 2025-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0021_alter_nitemresizetype_table_alter_nprocesstype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='nprocesstype',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nprocesstype',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
