# Generated by Django 5.1.3 on 2025-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0022_nprocesstype_created_by_nprocesstype_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nprocesstype',
            old_name='processNa',
            new_name='processName',
        ),
        migrations.AlterField(
            model_name='nprocesstype',
            name='processPipe',
            field=models.CharField(max_length=50),
        ),
    ]
