# Generated by Django 5.1.3 on 2025-01-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0023_rename_processna_nprocesstype_processname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nitemresizetype',
            old_name='nId',
            new_name='itmrz_id',
        ),
    ]
