# Generated by Django 5.1.3 on 2025-01-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0026_mtrsprocesstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAccountSummary',
            fields=[
                ('nID', models.BigAutoField(primary_key=True, serialize=False)),
                ('nACUSID', models.CharField(max_length=50)),
                ('nTickets', models.DecimalField(decimal_places=10, max_digits=20)),
                ('nPayment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nTotOutStand', models.DecimalField(decimal_places=4, max_digits=20)),
                ('nLastUDate', models.DateField(blank=True, null=True)),
                ('nCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('nCreatedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('nUpdatedDate', models.DateTimeField(auto_now=True)),
                ('nUpdatedBy', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
