# Generated by Django 5.1.3 on 2025-01-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibs', '0028_alter_naccountsummary_ntotoutstand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitem',
            name='nActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mmetal',
            name='nActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mmetalprocess',
            name='nActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mprocess',
            name='nActive',
            field=models.BooleanField(default=True),
        ),
    ]
